security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory:
            memory:
               users:
                  admin: { password: password, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login_firewall:
            pattern:   ^/admin/login$
            anonymous: ~

        main:
            pattern:    ^/admin/
            form_login:
                login_path: login
                check_path: login_check
